package controller;
import com.sun.net.httpserver.*; import dao.*; import model.*; import service.JobRecommendationService; import util.HttpUtil;
import java.io.*; import java.sql.*; import java.util.*;
public class ApiController implements HttpHandler {
 private final StudentDAO students=new StudentDAO(); private final JobDAO jobs=new JobDAO(); private final ApplicationDAO applications=new ApplicationDAO();
 public void handle(HttpExchange ex)throws IOException {try{String path=ex.getRequestURI().getPath().replace("/api/","");Map<String,String> p=HttpUtil.parameters(ex);
  if(path.equals("register"))register(ex,p); else if(path.equals("login"))login(ex,p); else if(path.equals("profile"))profile(ex,p); else if(path.equals("skills"))skills(ex,p); else if(path.equals("jobs"))jobs(ex,p); else if(path.equals("job"))job(ex,p); else if(path.equals("manage-job"))manageJob(ex,p); else if(path.equals("delete-job"))deleteJob(ex,p); else if(path.equals("apply"))apply(ex,p); else if(path.equals("applications"))applications(ex,p); else if(path.equals("admin-login"))adminLogin(ex,p); else if(path.equals("students"))studentList(ex); else if(path.equals("application-status"))status(ex,p); else HttpUtil.json(ex,404,"{\"error\":\"Unknown request\"}");
 }catch(SQLIntegrityConstraintViolationException e){HttpUtil.json(ex,400,"{\"error\":\"This email or record already exists.\"}");}catch(SQLException e){e.printStackTrace();HttpUtil.json(ex,500,"{\"error\":\"Database error. Check MySQL and DatabaseConnection.java.\"}");}catch(Exception e){HttpUtil.json(ex,400,"{\"error\":\""+HttpUtil.esc(e.getMessage())+"\"}");}}
 private boolean fields(HttpExchange e,Map<String,String>p,String...keys)throws IOException{for(String k:keys)if(p.get(k)==null||p.get(k).trim().isEmpty()){HttpUtil.json(e,400,"{\"error\":\"Please fill in all required fields.\"}");return false;}return true;}
 private void register(HttpExchange e,Map<String,String>p)throws Exception{if(!fields(e,p,"name","email","password"))return;if(!p.get("email").contains("@")){HttpUtil.json(e,400,"{\"error\":\"Enter a valid email address.\"}");return;}Student s=student(p);int id=students.register(s,p.get("password"));students.saveSkills(id,list(p.get("skills")));HttpUtil.json(e,200,"{\"message\":\"Registration successful. Please log in.\"}");}
 private void login(HttpExchange e,Map<String,String>p)throws Exception{if(!fields(e,p,"email","password"))return;Student s=students.login(p.get("email"),p.get("password"));if(s==null){HttpUtil.json(e,401,"{\"error\":\"Incorrect email or password.\"}");return;}HttpUtil.json(e,200,"{\"id\":"+s.id+",\"name\":\""+HttpUtil.esc(s.name)+"\"}");}
 private void profile(HttpExchange e,Map<String,String>p)throws Exception{int id=req(p,"studentId");if(e.getRequestMethod().equals("POST")){if(!fields(e,p,"name"))return;Student s=student(p);s.id=id;students.update(s);students.saveSkills(id,list(p.get("skills")));HttpUtil.json(e,200,"{\"message\":\"Profile updated.\"}");}else {Student s=students.get(id);if(s==null){HttpUtil.json(e,404,"{\"error\":\"Student not found\"}");return;}s.skills=students.skills(id);HttpUtil.json(e,200,studentJson(s));}}
 private void skills(HttpExchange e,Map<String,String>p)throws Exception{HttpUtil.json(e,200,array(jobs.allSkills()));}
 private void jobs(HttpExchange e,Map<String,String>p)throws Exception{List<Job> list=new JobRecommendationService().rank(jobs.all(),students.skills(req(p,"studentId")));String search=p.getOrDefault("search","").toLowerCase(),location=p.getOrDefault("location","").toLowerCase();int minimum=p.get("minimum")==null?0:req(p,"minimum");list.removeIf(j->(!search.isEmpty()&&!j.title.toLowerCase().contains(search)&&!j.company.toLowerCase().contains(search))||(!location.isEmpty()&&!j.location.toLowerCase().contains(location))||j.matchPercentage<minimum);HttpUtil.json(e,200,jobsJson(list));}
 private void job(HttpExchange e,Map<String,String>p)throws Exception{Job j=jobs.get(req(p,"id"));if(j==null){HttpUtil.json(e,404,"{\"error\":\"Job not found\"}");return;}j=new JobRecommendationService().rank(new ArrayList<>(List.of(j)),students.skills(req(p,"studentId"))).get(0);HttpUtil.json(e,200,jobJson(j));}
 private void manageJob(HttpExchange e,Map<String,String>p)throws Exception{if(!fields(e,p,"company","title","location","description","eligibility"))return;Job j=new Job();j.id=p.get("id")==null?0:req(p,"id");j.company=p.get("company");j.title=p.get("title");j.location=p.get("location");j.description=p.get("description");j.eligibility=p.get("eligibility");j.skills=list(p.get("skills"));jobs.save(j);HttpUtil.json(e,200,"{\"message\":\"Job saved successfully.\"}");}
 private void deleteJob(HttpExchange e,Map<String,String>p)throws Exception{jobs.delete(req(p,"id"));HttpUtil.json(e,200,"{\"message\":\"Job deleted.\"}");}
 private void apply(HttpExchange e,Map<String,String>p)throws Exception{boolean ok=applications.apply(req(p,"studentId"),req(p,"jobId"));HttpUtil.json(e,ok?200:400,ok?"{\"message\":\"Application submitted.\"}":"{\"error\":\"You have already applied for this job.\"}");}
 private void applications(HttpExchange e,Map<String,String>p)throws Exception{HttpUtil.json(e,200,records(p.get("studentId")==null?applications.all():applications.byStudent(req(p,"studentId"))));}
 private void adminLogin(HttpExchange e,Map<String,String>p)throws Exception{if(!fields(e,p,"username","password"))return;try(Connection c=util.DatabaseConnection.getConnection();PreparedStatement s=c.prepareStatement("SELECT admin_id FROM admins WHERE username=? AND password=?")){s.setString(1,p.get("username"));s.setString(2,p.get("password"));ResultSet r=s.executeQuery();if(r.next())HttpUtil.json(e,200,"{\"id\":"+r.getInt(1)+"}");else HttpUtil.json(e,401,"{\"error\":\"Incorrect admin credentials.\"}");}}
 private void studentList(HttpExchange e)throws Exception{List<Student>x=students.all();StringBuilder b=new StringBuilder("[");for(Student s:x){if(b.length()>1)b.append(',');b.append(studentJson(s));}HttpUtil.json(e,200,b.append(']').toString());}
 private void status(HttpExchange e,Map<String,String>p)throws Exception{applications.status(req(p,"id"),p.get("status"));HttpUtil.json(e,200,"{\"message\":\"Status updated.\"}");}
 private Student student(Map<String,String>p){Student s=new Student();s.name=p.getOrDefault("name","");s.email=p.getOrDefault("email","");s.phone=p.getOrDefault("phone","");s.qualification=p.getOrDefault("qualification","");s.graduationYear=p.getOrDefault("graduationYear","");return s;}
 private int req(Map<String,String>p,String k){Integer n=HttpUtil.number(p,k);if(n==null)throw new IllegalArgumentException("Missing or invalid "+k);return n;}
 private List<String>list(String s){return s==null||s.isBlank()?new ArrayList<>():Arrays.asList(s.split(","));}
 private String array(List<String>x){StringBuilder b=new StringBuilder("[");for(String s:x){if(b.length()>1)b.append(',');b.append('"').append(HttpUtil.esc(s)).append('"');}return b.append(']').toString();}
 private String studentJson(Student s){return "{\"id\":"+s.id+",\"name\":\""+HttpUtil.esc(s.name)+"\",\"email\":\""+HttpUtil.esc(s.email)+"\",\"phone\":\""+HttpUtil.esc(s.phone)+"\",\"qualification\":\""+HttpUtil.esc(s.qualification)+"\",\"graduationYear\":\""+HttpUtil.esc(s.graduationYear)+"\",\"skills\":"+array(s.skills)+"}";}
 private String jobJson(Job j){return "{\"id\":"+j.id+",\"company\":\""+HttpUtil.esc(j.company)+"\",\"title\":\""+HttpUtil.esc(j.title)+"\",\"location\":\""+HttpUtil.esc(j.location)+"\",\"description\":\""+HttpUtil.esc(j.description)+"\",\"eligibility\":\""+HttpUtil.esc(j.eligibility)+"\",\"postedDate\":\""+j.postedDate+"\",\"skills\":"+array(j.skills)+",\"match\":"+j.matchPercentage+"}";}
 private String jobsJson(List<Job>x){StringBuilder b=new StringBuilder("[");for(Job j:x){if(b.length()>1)b.append(',');b.append(jobJson(j));}return b.append(']').toString();}
 private String records(List<Map<String,String>>x){StringBuilder b=new StringBuilder("[");for(Map<String,String>m:x){if(b.length()>1)b.append(',');b.append('{');for(Map.Entry<String,String>z:m.entrySet()){if(b.charAt(b.length()-1)!='{')b.append(',');b.append('"').append(z.getKey()).append("\":\"").append(HttpUtil.esc(z.getValue())).append('"');}b.append('}');}return b.append(']').toString();}
}
