package dao;
import model.Job; import util.DatabaseConnection; import java.sql.*; import java.util.*;
public class JobDAO {
 public List<String> allSkills()throws SQLException{List<String>x=new ArrayList<>();try(Connection c=DatabaseConnection.getConnection();Statement s=c.createStatement();ResultSet r=s.executeQuery("SELECT skill_name FROM skills ORDER BY skill_name")){while(r.next())x.add(r.getString(1));}return x;}
 public List<Job> all()throws SQLException{List<Job>x=new ArrayList<>();try(Connection c=DatabaseConnection.getConnection();Statement s=c.createStatement();ResultSet r=s.executeQuery("SELECT * FROM jobs ORDER BY posted_date DESC")){while(r.next())x.add(read(r));}for(Job j:x)j.skills=skills(j.id);return x;}
 public Job get(int id)throws SQLException{try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement("SELECT * FROM jobs WHERE job_id=?")){p.setInt(1,id);ResultSet r=p.executeQuery();if(!r.next())return null;Job j=read(r);j.skills=skills(id);return j;}}
 public void save(Job j)throws SQLException{String q=j.id==0?"INSERT INTO jobs(company_name,job_title,location,job_description,eligibility,posted_date) VALUES(?,?,?,?,?,CURDATE())":"UPDATE jobs SET company_name=?,job_title=?,location=?,job_description=?,eligibility=? WHERE job_id=?";try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement(q,Statement.RETURN_GENERATED_KEYS)){p.setString(1,j.company);p.setString(2,j.title);p.setString(3,j.location);p.setString(4,j.description);p.setString(5,j.eligibility);if(j.id==0){p.executeUpdate();ResultSet k=p.getGeneratedKeys();k.next();j.id=k.getInt(1);}else{p.setInt(6,j.id);p.executeUpdate();}saveSkills(c,j);}}
 private void saveSkills(Connection c,Job j)throws SQLException{try(PreparedStatement d=c.prepareStatement("DELETE FROM job_skills WHERE job_id=?")){d.setInt(1,j.id);d.executeUpdate();}try(PreparedStatement i=c.prepareStatement("INSERT INTO job_skills(job_id,skill_id) SELECT ?,skill_id FROM skills WHERE skill_name=?")){for(String x:j.skills){i.setInt(1,j.id);i.setString(2,x);i.addBatch();}i.executeBatch();}}
 public void delete(int id)throws SQLException{try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement("DELETE FROM jobs WHERE job_id=?")){p.setInt(1,id);p.executeUpdate();}}
 private List<String> skills(int id)throws SQLException{List<String>x=new ArrayList<>();String q="SELECT skill_name FROM skills s JOIN job_skills js ON s.skill_id=js.skill_id WHERE js.job_id=?";try(Connection c=DatabaseConnection.getConnection();PreparedStatement p=c.prepareStatement(q)){p.setInt(1,id);ResultSet r=p.executeQuery();while(r.next())x.add(r.getString(1));}return x;}
 private Job read(ResultSet r)throws SQLException{Job j=new Job();j.id=r.getInt("job_id");j.company=r.getString("company_name");j.title=r.getString("job_title");j.location=r.getString("location");j.description=r.getString("job_description");j.eligibility=r.getString("eligibility");j.postedDate=r.getString("posted_date");return j;}
}
